spring:
  datasource:
    url: jdbc:mysql://localhost:3306/berry
    username: root
    password: Wldnjs1!@
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: user
#      password: 1111
#      roles: USER
  # jpa setting
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
  thymeleaf:
    cache: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
