spring:
  datasource:
    url: jdbc:mysql://localhost:3306/berry
    username: root
    password: Wldnjs1!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 1111